version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 notes_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
  db:
    image: postgres
    environment:
      POSTGRES_DB: koyebdb
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: QS2Riwj0gkoC
      POSTGRES_HOST: ep-autumn-shape-a2fl96f4.eu-central-1.pg.koyeb.app
      POSTGRES_PORT: 5432
